services:
  - type: web
    name: wikiclip-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python migrations.py
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

databases:
  - name: wikiclip-db
    databaseName: wikiclip
    ipAllowList: []  # only allow internal connections